# Sample set of values. Please generate your own values using the compute_calibration script included in this package
mag_bias:
     x: 0.183117
     y: 0.273127
     z: -0.761884
     radius: 0.271064
