// Generated by gencpp from file gpspub/radardata.msg
// DO NOT EDIT!


#ifndef GPSPUB_MESSAGE_RADARDATA_H
#define GPSPUB_MESSAGE_RADARDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gpspub
{
template <class ContainerAllocator>
struct radardata_
{
  typedef radardata_<ContainerAllocator> Type;

  radardata_()
    : RadarData()  {
      RadarData.assign(0.0);
  }
  radardata_(const ContainerAllocator& _alloc)
    : RadarData()  {
  (void)_alloc;
      RadarData.assign(0.0);
  }



   typedef boost::array<double, 32>  _RadarData_type;
  _RadarData_type RadarData;





  typedef boost::shared_ptr< ::gpspub::radardata_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gpspub::radardata_<ContainerAllocator> const> ConstPtr;

}; // struct radardata_

typedef ::gpspub::radardata_<std::allocator<void> > radardata;

typedef boost::shared_ptr< ::gpspub::radardata > radardataPtr;
typedef boost::shared_ptr< ::gpspub::radardata const> radardataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gpspub::radardata_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gpspub::radardata_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gpspub::radardata_<ContainerAllocator1> & lhs, const ::gpspub::radardata_<ContainerAllocator2> & rhs)
{
  return lhs.RadarData == rhs.RadarData;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gpspub::radardata_<ContainerAllocator1> & lhs, const ::gpspub::radardata_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gpspub

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::gpspub::radardata_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gpspub::radardata_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gpspub::radardata_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gpspub::radardata_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gpspub::radardata_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gpspub::radardata_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gpspub::radardata_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3bdcd1bf0fe69ee97213b20c034863f7";
  }

  static const char* value(const ::gpspub::radardata_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3bdcd1bf0fe69ee9ULL;
  static const uint64_t static_value2 = 0x7213b20c034863f7ULL;
};

template<class ContainerAllocator>
struct DataType< ::gpspub::radardata_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gpspub/radardata";
  }

  static const char* value(const ::gpspub::radardata_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gpspub::radardata_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[32] RadarData\n"
;
  }

  static const char* value(const ::gpspub::radardata_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gpspub::radardata_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.RadarData);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct radardata_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gpspub::radardata_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gpspub::radardata_<ContainerAllocator>& v)
  {
    s << indent << "RadarData[]" << std::endl;
    for (size_t i = 0; i < v.RadarData.size(); ++i)
    {
      s << indent << "  RadarData[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.RadarData[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // GPSPUB_MESSAGE_RADARDATA_H
